version: '3'
services:
  cassandra:
      image: cassandra
      ports:
        - 9042:9042
  prometheus:
      image: prom/prometheus
      ports:
        - 9090:9090
      volumes:
        - ./prometheus:/etc/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yaml'
  grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
